In [20]:
import pandas as pd

df = pd.read_csv("../data/raw/superstore_raw.csv", encoding='latin1')

In [2]:
df.head()

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,è®°å½æ°,Order.Date,Order.ID,...,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07 00:00:00.000,CA-2011-130813,...,19,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21 00:00:00.000,CA-2011-148614,...,19,Consumer,2011-01-26 00:00:00.000,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,21,Consumer,2011-08-09 00:00:00.000,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,111,Consumer,2011-08-09 00:00:00.000,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29 00:00:00.000,CA-2011-146969,...,6,Consumer,2011-10-03 00:00:00.000,Standard Class,1.32,California,Paper,2011,North America,40

In [22]:
df.columns

Index(['Category', 'City', 'Country', 'Customer.ID', 'Customer.Name',
       'Discount', 'Market', 'è®°å½æ°', 'Order.Date', 'Order.ID',
       'Order.Priority', 'Product.ID', 'Product.Name', 'Profit', 'Quantity',
       'Region', 'Row.ID', 'Sales', 'Segment', 'Ship.Date', 'Ship.Mode',
       'Shipping.Cost', 'State', 'Sub.Category', 'Year', 'Market2', 'weeknum'],
      dtype='object')

In [23]:
df.shape

(51290, 27)

In [24]:
#Checking Missing Values
df.isnull().sum()

Category          0
City              0
Country           0
Customer.ID       0
Customer.Name     0
Discount          0
Market            0
è®°å½æ°         0
Order.Date        0
Order.ID          0
Order.Priority    0
Product.ID        0
Product.Name      0
Profit            0
Quantity          0
Region            0
Row.ID            0
Sales             0
Segment           0
Ship.Date         0
Ship.Mode         0
Shipping.Cost     0
State             0
Sub.Category      0
Year              0
Market2           0
weeknum           0
dtype: int64

In [25]:
#Checking Duplicates
df.duplicated().sum()

np.int64(0)

**Data Cleaning**

In [26]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace('.', '_')
df.columns = df.columns.str.replace(' ', '_')
df.columns

Index(['category', 'city', 'country', 'customer_id', 'customer_name',
       'discount', 'market', 'è®°å½æ°', 'order_date', 'order_id',
       'order_priority', 'product_id', 'product_name', 'profit', 'quantity',
       'region', 'row_id', 'sales', 'segment', 'ship_date', 'ship_mode',
       'shipping_cost', 'state', 'sub_category', 'year', 'market2', 'weeknum'],
      dtype='object')

In [27]:
df = df.drop(columns=['è®°å½æ°'])

In [28]:
df.columns

Index(['category', 'city', 'country', 'customer_id', 'customer_name',
       'discount', 'market', 'order_date', 'order_id', 'order_priority',
       'product_id', 'product_name', 'profit', 'quantity', 'region', 'row_id',
       'sales', 'segment', 'ship_date', 'ship_mode', 'shipping_cost', 'state',
       'sub_category', 'year', 'market2', 'weeknum'],
      dtype='object')

In [29]:
df['order_date'] = pd.to_datetime(df['order_date'])
df['ship_date'] = pd.to_datetime(df['ship_date'])

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   category        51290 non-null  object
 1   city            51290 non-null  object
 2   country         51290 non-null  object
 3   customer_id     51290 non-null  object
 4   customer_name   51290 non-null  object
 5   discount        51290 non-null  float64
 6   market          51290 non-null  object
 7   order_date      51290 non-null  datetime64[ns]
 8   order_id        51290 non-null  object
 9   order_priority  51290 non-null  object
 10  product_id      51290 non-null  object
 11  product_name    51290 non-null  object
 12  profit          51290 non-null  float64
 13  quantity        51290 non-null  int64
 14  region          51290 non-null  object
 15  row_id          51290 non-null  int64
 16  sales           51290 non-null  int64
 17  segment         51290 non-null  object
 18  ship_date       51290 non-null  datetime64[ns]
 19  ship_mode       51290 non-null  object
 20  shipping_cost   51290 non-null  float64
 21  state           51290 non-null  object
 22  sub_category    51290 non-null  object
 23  year            51290 non-null  int64
 24  market2         51290 non-null  object
 25  weeknum         51290 non-null  int64
dtypes: datetime64[ns](2), float64(3), int64(5), object(16)
memory usage: 10.2+ MB

In [31]:
# Removing Unnecessary Columns
df = df.drop(columns=['row_id', 'market2', 'year', 'weeknum'])

In [32]:
# Creating New Columns
df['order_year'] = df['order_date'].dt.year
df['order_month'] = df['order_date'].dt.month
df['order_day'] = df['order_date'].dt.day
df['month_name'] = df['order_date'].dt.month_name()

In [33]:
df.head()

,category,city,country,customer_id,customer_name,discount,market,order_date,order_id,order_priority,...,segment,ship_date,ship_mode,shipping_cost,state,sub_category,order_year,order_month,order_day,month_name
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,2011-01-07,CA-2011-130813,High,...,Consumer,2011-01-09,Second Class,4.37,California,Paper,2011,1,7,January
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,2011-01-21,CA-2011-148614,Medium,...,Consumer,2011-01-26,Standard Class,0.94,California,Paper,2011,1,21,January
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,2011-08-05,CA-2011-118962,Medium,...,Consumer,2011-08-09,Standard Class,1.81,California,Paper,2011,8,5,August
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,2011-08-05,CA-2011-118962,Medium,...,Consumer,2011-08-09,Standard Class,4.59,California,Paper,2011,8,5,August
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,2011-09-29,CA-2011-146969,High,...,Consumer,2011-10-03,Standard Class,1.32,California,Paper,2011,9,29,September

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   category        51290 non-null  object
 1   city            51290 non-null  object
 2   country         51290 non-null  object
 3   customer_id     51290 non-null  object
 4   customer_name   51290 non-null  object
 5   discount        51290 non-null  float64
 6   market          51290 non-null  object
 7   order_date      51290 non-null  datetime64[ns]
 8   order_id        51290 non-null  object
 9   order_priority  51290 non-null  object
 10  product_id      51290 non-null  object
 11  product_name    51290 non-null  object
 12  profit          51290 non-null  float64
 13  quantity        51290 non-null  int64
 14  region          51290 non-null  object
 15  sales           51290 non-null  int64
 16  segment         51290 non-null  object
 17  ship_date       51290 non-null  datetime64[ns]
 18  ship_mode       51290 non-null  object
 19  shipping_cost   51290 non-null  float64
 20  state           51290 non-null  object
 21  sub_category    51290 non-null  object
 22  order_year      51290 non-null  int32
 23  order_month     51290 non-null  int32
 24  order_day       51290 non-null  int32
 25  month_name      51290 non-null  object
dtypes: datetime64[ns](2), float64(3), int32(3), int64(2), object(16)
memory usage: 9.6+ MB

In [35]:
# Saving the cleaned data
df.to_csv("../data/cleaned/superstore_cleaned.csv", index=False)